# Generated by Django 6.0.3 on 2026-04-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('M', 'Moderator'), ('C', 'Customer')], default='C', max_length=1),
        ),
    ]
