# Generated by Django 6.0.3 on 2026-03-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=20, verbose_name=[('protein', 'Protein'), ('creatine', 'Creatine'), ('vitamin', 'Vitamin'), ('preworkout', 'Pre Workout'), ('fatburner', 'Fat Burner'), ('gainers', 'Gainers'), ('aminoacids', 'Amino Acids'), ('collagen', 'Collagen'), ('testosteronbooster', 'Testosteron Booster'), ('accessories', 'Accessories'), ('weightloss', 'Weight Loss')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, help_text='in grams/kilograms', null=True),
        ),
    ]
