# Generated by Django 6.0.3 on 2026-03-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Protein', 'Protein'), ('creatine', 'Creatine'), ('vitamin', 'Vitamin'), ('preworkout', 'Pre Workout'), ('fatburner', 'Fat Burner'), ('gainers', 'Gainers'), ('aminoacids', 'Amino Acids'), ('collagen', 'Collagen'), ('testosteronbooster', 'Testosteron Booster'), ('accessories', 'Accessories'), ('weightloss', 'Weight Loss')], max_length=20),
        ),
    ]
