# Generated by Django 6.0.3 on 2026-03-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Protein', 'Protein'), ('Creatine', 'Creatine'), ('Vitamin', 'Vitamin'), ('Pre Workout', 'Pre Workout'), ('Fat Burner', 'Fat Burner'), ('Gainers', 'Gainers'), ('Amino Acids', 'Amino Acids'), ('Collagen', 'Collagen'), ('Testosteron Booster', 'Testosteron Booster'), ('Accessories', 'Accessories'), ('Weight Loss', 'Weight Loss')], max_length=20),
        ),
    ]
