# Generated by Django 6.0.3 on 2026-04-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Shiko'), ('shipped', 'Në rrugë'), ('delivered', 'Marrë')], default='pending', max_length=20),
        ),
    ]
